// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package moneyforward

import (
	"github.com/mpyw/moneyforward-paypaysec-bridge-action/v3/internal/application/domain/asset"
	"github.com/mpyw/moneyforward-paypaysec-bridge-action/v3/internal/application/usecase/syncassets"
	"github.com/mpyw/moneyforward-paypaysec-bridge-action/v3/internal/infra/moneyforward/manualasset"
)

// Injectors from wire.go:

// newSyncFromEntries assembles the real sync use case against a broker that
// reports what was typed and a ledger already holding a session.
//
// The same use case the scheduled job runs, deliberately: a command that
// reconciled on its own would be testing something other than what runs.
//
// Not the same graph, though, and not shareable with the job's: the broker, the
// ledger and the reporter are all different implementations, so an injector
// covering both would take those three as arguments and be a struct literal
// with extra steps. Named for what it builds rather than left as a second
// newSync, since the two mean different things.
func newSyncFromEntries(desired []asset.Asset, acct manualasset.Account) syncassets.Sync {
	v := provideBridges(desired, acct)
	reporter := provideReporter()
	bool2 := provideAllowEmpty(desired)
	sync := syncassets.Sync{
		Bridges:    v,
		Reporter:   reporter,
		AllowEmpty: bool2,
	}
	return sync
}
