// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package manulife

import (
	"context"
	"github.com/mpyw/moneyforward-paypaysec-bridge-action/v3/internal/cli/commands/debug/session"
)

// Injectors from wire.go:

// newSignIn assembles the site client and where its one-time code comes from.
func newSignIn(ctx context.Context, opts *session.Options) (signIn, error) {
	manulifeCredentials, err := provideCredentials(opts)
	if err != nil {
		return signIn{}, err
	}
	client := provideClient(manulifeCredentials)
	source := provideCodes(ctx, opts)
	manulifeSignIn := signIn{
		client: client,
		codes:  source,
	}
	return manulifeSignIn, nil
}
