// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gmail

import (
	"github.com/mpyw/moneyforward-paypaysec-bridge-action/internal/application/usecase/authorizegmail"
)

// Injectors from wire.go:

// newAuthorize assembles the consent flow, where the credential goes, and the
// check that it opens the mailbox somebody meant.
func newAuthorize(client clientFile, out credentialFile) authorizegmail.Authorize {
	consentFlow := provideConsent(client)
	credentialStore := provideCredentialStore(out)
	portMailboxOpener := provideMailboxOpener()
	authorize := authorizegmail.Authorize{
		Consent: consentFlow,
		Store:   credentialStore,
		Verify:  portMailboxOpener,
	}
	return authorize
}
