// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package paypaysec

import (
	"context"
	"github.com/mpyw/moneyforward-paypaysec-bridge-action/internal/cli/commands/debug/session"
)

// Injectors from wire.go:

// newClient assembles the site client and where its one-time code comes from.
//
// There is no use case here, and this package is the only one where that is
// true. Its two substantive commands are deliberately not the port: `login` is
// a single port operation, and `balance` exists precisely to do what the port
// will not — read all eight targets and show the ones that failed, rather than
// stopping at the first. Wrapping either would remove the reason it exists.
//
// The assembly is still assembly, though, and "where is this put together"
// should have the same answer here as everywhere else.
func newSignIn(ctx context.Context, opts *session.Options) (signIn, error) {
	paypaysecCredentials, err := provideCredentials(opts)
	if err != nil {
		return signIn{}, err
	}
	client := provideClient(paypaysecCredentials)
	source := provideCodes(ctx, opts)
	paypaysecSignIn := signIn{
		client: client,
		codes:  source,
	}
	return paypaysecSignIn, nil
}
