// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sync

import (
	"context"
	"github.com/mpyw/moneyforward-paypaysec-bridge-action/v3/internal/application/usecase/syncassets"
	"github.com/mpyw/moneyforward-paypaysec-bridge-action/v3/internal/infra/actionslog"
)

// Injectors from wire.go:

// newSync assembles the scheduled job's dependencies.
//
// The list is the whole specification — wire works out the order and the
// plumbing from the providers' signatures. What that buys here is not saved
// keystrokes but a compile-time failure when the graph stops making sense: a
// provider that starts needing something nothing supplies, or two that supply
// the same type, is an error at generation rather than a nil at four in the
// afternoon on a Monday.
//
// The returned cleanup closes the browser.
func newSync(ctx context.Context) (syncassets.Sync, func(), error) {
	masker := _wireMaskerValue
	config, err := provideConfig(masker)
	if err != nil {
		return syncassets.Sync{}, nil, err
	}
	mailSearcher, err := provideMailbox(ctx, masker)
	if err != nil {
		return syncassets.Sync{}, nil, err
	}
	syncBrowserContext, cleanup, err := provideBrowserContext(ctx, config, mailSearcher)
	if err != nil {
		return syncassets.Sync{}, nil, err
	}
	syncMoneyForwardCodes := provideMoneyForwardCodes(mailSearcher, masker)
	moneyForwardSession := provideMoneyForwardSession(config, syncBrowserContext, syncMoneyForwardCodes)
	syncPayPaySecCodes := providePayPaySecCodes(mailSearcher, masker)
	syncManulifeCodes := provideManulifeCodes(mailSearcher, masker)
	v, err := provideBridges(config, syncBrowserContext, moneyForwardSession, syncPayPaySecCodes, syncManulifeCodes, masker)
	if err != nil {
		cleanup()
		return syncassets.Sync{}, nil, err
	}
	portReporter := provideReporter(masker)
	bool2 := provideAllowEmptyingCategories(config)
	sync := syncassets.Sync{
		Bridges:                 v,
		Reporter:                portReporter,
		AllowEmptyingCategories: bool2,
	}
	return sync, func() {
		cleanup()
	}, nil
}

var (
	_wireMaskerValue = actionslog.Masker{}
)
